apiVersion: v1
kind: Secret
metadata:
  name: kraken-agent
type: Opaque
data:
  tls.crt: {{ .Files.Get "cert/tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "cert/tls.key" | b64enc }}
  passphrase: {{ .Files.Get "cert/passphrase" | b64enc }}
