kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:kraken
rules:
  - verbs:
      - use
    apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - kraken
