extends: /etc/kraken/config/build-index/base.yaml
{{ include "tls" . }}
{{ include "build-index-cluster" . }}
{{ include "origins" . }}
{{ include "metrics" . }}

backends:
{{ with .Values.build_index.extraBackends }}{{ tpl . $ | indent 2 }}{{ end }}

remotes: {}

tag_replication:
  retry_interval: 100ms
  poll_retries_interval: 250ms

tag_types:
  - namespace: .*
    type: docker
    root: tags

tag_store:
  write_through: false

writeback:
  retry_interval: 100ms
  poll_retries_interval: 250ms

nginx:
  cache_dir: /tmp/kraken-build-index-nginx/
